### ISSUE TITLE
CheckForUpdateHelper - simplify logging for SocketTimeoutException

### ISSUE THREAD

**Issue by sherriff** [Cantara/Java-Auto-Update#28]
1. CheckForUpdateHelper - simplify logging for SocketTimeoutException and UnknownHostException, the stacktrace is not needed. 
2. Use exponential backoff (max backoff 15min?) if simple to implement

SocketTimeoutException

2016-10-17T07:05:07.989+0200 [pool-2-thread-1] WARN n.c.jau.coms.CheckForUpdateHelper - checkForUpdate failed, do nothing. Retrying in 60 seconds. java.net.SocketTimeoutException: Read timed out at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_72] at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_72] at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_72] at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_72] at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_72] at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_72] at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973) ~[na:1.8.0_72] at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930) ~[na:1.8.0_72] at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_72] at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_72] at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_72] at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_72] at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704) ~[na:1.8.0_72] at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[na:1.8.0_72] at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789) ~[na:1.8.0_72] at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[na:1.8.0_72] at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536) ~[na:1.8.0_72] at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_72] at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_72] at java.net.HttpURLConnection.getResponseMessage(HttpURLConnection.java:546) ~[na:1.8.0_72] at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:382) ~[na:1.8.0_72] at no.cantara.cs.client.ConfigServiceClient.checkForUpdate(ConfigServiceClient.java:199) ~[java-auto-update-0.8.jar:na] at no.cantara.jau.coms.CheckForUpdateHelper.lambda$getCheckForUpdateRunnable$0(CheckForUpdateHelper.java:52) ~[java-auto-update-0.8.jar:na] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_72] at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_72] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_72] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_72] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_72] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_72] at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_72]

---

UnknownHostException: 

2016-10-17T00:34:40.864+0200 [pool-2-thread-1] WARN n.c.jau.coms.CheckForUpdateHelper - checkForUpdate failed, do nothing. Retrying in 60 seconds. java.net.UnknownHostException: flow.quant.embriq.no at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_72] at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_72] at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_72] at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_72] at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) ~[na:1.8.0_72] at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_72] at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_72] at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_72] at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[na:1.8.0_72] at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[na:1.8.0_72] at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.8.0_72] at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105) ~[na:1.8.0_72] at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_72] at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_72] at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283) ~[na:1.8.0_72] at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258) ~[na:1.8.0_72] at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250) ~[na:1.8.0_72] at no.cantara.cs.client.ConfigServiceClient.checkForUpdate(ConfigServiceClient.java:195) ~[java-auto-update-0.8.jar:na] at no.cantara.jau.coms.CheckForUpdateHelper.lambda$getCheckForUpdateRunnable$0(CheckForUpdateHelper.java:52) ~[java-auto-update-0.8.jar:na] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_72] at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_72] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_72] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_72] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_72] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_72] at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_72]

**Comment by kgrodzicki** [comment]
Added commit which fix point 1. 
Point 2 needs quite a lot rewriting of current implementation. 60 seconds is already quite ok retry delay. Should we go for exponential backoff anyways ?
